export const API_CONSTANTS = {
    SIGNUP: "users",
    LOGIN: "users/sign_in",
    LOGOUT: "users/sign_out",
    FORGOT_PASSWORD: "users/password",
    RESET_PASSWORD: "users/password",

    // Admin use
    COMMON_CATEGORIES_URL: "api/v1/categories",
    COMMON_SUB_CATEGORIES_URL: "api/v1/sub_categories",
    COMMON_PRODUCTS_URL: "api/v1/products",
    COMMON_INVENTORY_URL: "api/v1/inventories",
    COMMON_ORDER_URL: "api/v1/orders",
    COMMON_COUPON_URL: "api/v1/coupons",
    COMMON_REPORT_URL: "api/v1/reports",
    COMMON_DISCOUNT_URL: "api/v1/discounts",
    COMMON_USERS_URL: "api/v1/users",
    COMMON_ADRESESS_URL: "api/v1/addresses",
    COMMON_ADMIN_DASHBOARD_URL: "api/v1/dashboard",
    COMMON_BLOGS_URL: "api/v1/blogs",
    COMMON_PRODUCT_REVIEW_URL: "api/v1/product_reviews",
    COMMON_FEST_PRODUCTS_URL: "api/v1/fest_specials",
    COMMON_SUBSCIBER_URL: "api/v1/subscribers",
    COMMON_CUSTOMER_ENQUIRY_URL: "api/v1/contact_details",
    
    // General use
    BLOGS_URL: "api/v1/user_dashboard/latest_blogs",
    SNACK_RANGE_URL : "api/v1/user_dashboard/snacks_category",
    SPECIALITY_CATEGORY_URL : "api/v1/user_dashboard/speciality_category",
    GIFTING_CATEGORY_URL : "api/v1/user_dashboard/gifting_category",
    ALL_CATEGORY_URL : "api/v1/user_dashboard/all_categories",
    ALL_PRODUCTS_URL : "api/v1/user_dashboard/all_active_products",
    MENU_LIST_URL: "api/v1/user_dashboard/nav_menu_list",
    GET_PRODUCT_BY_SUBCATEGORY_ID_URL: "api/v1/user_dashboard/get_products_by_subcategory",
    ALL_SUB_CATEGORY_URL : "api/v1/user_dashboard/all_sub_categories",
    PRODUCT_REVIEW_URL : "api/v1/user_dashboard/add_user_review",
    PRODUCT_REVIEW_BY_ID_URL : "api/v1/user_dashboard/get_product_review_by_id",
    ACTIVE_FEST_SPECIAL: "api/v1/user_dashboard/get_active_fest_special",
    SUBSCRIBE_USER_BY_MAIL_URL: "api/v1/user_dashboard/subscribe_user_by_email",
    SEND_PHONE_OTP_URL: "api/v1/user_dashboard/send_user_otp",
    VERIFY_PHONE_OTP_URL: "api/v1/user_dashboard/verify_user_otp",
    PAYMENT_INTENT_CREATE: "api/v1/payment_transactions/create_payment_intent",
    PAYMENT_VERIFY: "api/v1/payment_transactions/verify_payment",
    ADD_CONTACT_DETAILS: "api/v1/user_dashboard/add_contact_details",
    GET_ALL_SUBCATEGORY_BY_CATEGORY_NAME_URL: "api/v1/user_dashboard/get_subcategories_by_category_name",
    GET_PRODUCT_BY_CATEGORY_NAME_URL: "api/v1/user_dashboard/get_products_by_category_name",
    GET_PRODUCT_BY_SUB_CATEGORY_NAME_URL: "api/v1/user_dashboard/get_products_by_subcategory_name",
    GET_PRODUCT_BY_FESTIVAL_SPECIAL_NAME_URL: "api/v1/user_dashboard/get_products_by_festival_special_name"
}