import Topbar from '@common/Topbar';
import Sidebar from '@common/Sidebar';
import CategoryList from '@adminpage-layouts/Category/CategoryList';
import CategoryForm from '@adminpage-layouts/Category/CategoryForm';
import SubCategoryList from '@adminpage-layouts/SubCategory/SubCategoryList';
import SubCategoryForm from '@adminpage-layouts/SubCategory/SubCategoryForm';
import InventoryList from '@adminpage-layouts/Inventory/InventoryList';
import InventoryForm from '@adminpage-layouts/Inventory/InventoryForm';
import ProductList from '@adminpage-layouts/Product/ProductList';
import ProductForm from '@adminpage-layouts/Product/ProductForm';
import DashboardStats from '@adminpage-layouts/DashboardStats/DashboardStats.jsx';
import OrderList from '@adminpage-layouts/Order/OrderList';
import OrderForm from '@adminpage-layouts/Order/OrderForm';
import OrderView from '@adminpage-layouts/Order/OrderView';
import CouponList from '@adminpage-layouts/Coupon/CouponList';
import CouponForm from '@adminpage-layouts/Coupon/CouponForm';
import DiscountForm from '@adminpage-layouts/Discount/DiscountForm';
import DiscountList from '@adminpage-layouts/Discount/DiscountList';
import UserList from '@adminpage-layouts/User/UserList';
import BlogList from '@adminpage-layouts/Blog/BlogList';
import FestivalSpecialForm from '@adminpage-layouts/FestivalSpecial/FestivalSpecialForm';
import FestivalSpecialList from '@adminpage-layouts/FestivalSpecial/FestivalSpecialList';
import ReviewList from '@adminpage-layouts/Review/ReviewList';
import SubscriberList from '@adminpage-layouts/Subscriber/SubscriberList';
import CustomerEnquiryList from '@adminpage-layouts/CustomerEnquiry/CustomerEnquiryList';

export { Topbar, Sidebar, CategoryList, CategoryForm, SubCategoryList, SubCategoryForm, ProductList, ProductForm, InventoryList, InventoryForm, DashboardStats, OrderList, OrderForm, OrderView, CouponList, CouponForm, DiscountForm, DiscountList, UserList, BlogList, FestivalSpecialList, FestivalSpecialForm, ReviewList, SubscriberList, CustomerEnquiryList };